HGH for Carbon (C) in PBE with NLCC,generated by Saha,2015
    6    4  20150303 zatom, zion, date (yymmdd)
   12   -101130  0 0 2002 0         pspcod, ixc, lmax, lloc, mmax, r2well
    0.41329225352  2 -5.729305064  0.874750285642 rloc nloc c1 .. cnloc
   1                                                      nsep
   0.4341053017   2   9.01955484658 -2.4185793675      s-projector
                       0.554729349186
    0.362404633914     0.60557630341      rcore, qcore (nlcc)
